version: '3.3'
services:
  db:
    image: mariadb:10.3.9
    restart: always
    container_name: filament-db
    # command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filament
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - my-bridge-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: filament-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - my-bridge-network
networks:
  my-bridge-network:
    # external: true
    driver: bridge
